<!DOCTYPE HTML>
<html>
 <head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="/stylesheets/style.css" type="text/css">
  <title>Link-shredder</title>
 </head>
 <body link="black" vlink="black">
    <div id="header">
        <a class="decor" href="/"><h1>Link-shredder</h1></a>
    </div>
    <div class="treatment">
        <p>Sorry, the service is temporarily on treatment.</p>
    </div>
 </body>
</html>